PAAS-1282: Add HTTP Security Headers to Haproxy  on update
Jahia/cloud-scripts pull request #64
Opened 2020-12-02 23:37 UTC by amitc-jahia

JIRA issue: https://jira.jahia.org/browse/PAAS-1282

Short description:
Add HTTP Security Response Headers at HAProxy level on update

2020-12-03 12:41 UTC, laurentfufu requested changes

2020-12-03 12:41 UTC, laurentfufu commented on jahia-cloud-env-update/update-to-3.2.0/update.yml
> +      service haproxy reload
```suggestion
      insert_line_1='    http-response set-header Strict-Transport-Security "max-age=63072000;"'
      insert_line_2='    http-response set-header X-Content-Type-Options "nosniff"'
      insert_line_3='    http-response set-header X-XSS-Protection "1; mode=block;"'
      if ! (grep -qPzo "$insert_line_1\n$insert_line_2\n$insert_line_3" /etc/haproxy/haproxy.cfg.d/00-global.cfg); then
        echo "headers already there"
        exit 0
      fi
      pattern='(Host) len 50'
      sed -i.bak "/$pattern/a\\\n$insert_line_1\n$insert_line_2\n$insert_line_3" /etc/haproxy/haproxy.cfg.d/00-global.cfg
      chown haproxy: /etc/haproxy/00-global.cfg.bak
      service haproxy reload
```
not sure about the `.bak` is relevant here but why not.

the added `grep` is not tested but should be use for  not having several time the headers line if manifest have to be applied several time on an env.

2020-12-03 12:49 UTC, kevinvandel commented on jahia-cloud-env-update/update-to-3.2.0/update.yml
> +    user: root
No newline at end of file :scream:

2020-12-03 13:25 UTC, Ronan-Gorain commented on jahia-cloud-env-update/update-to-3.2.0/update.yml
> +      pattern='(Host) len 50'
This pattern could be used in customer rewrite rules which are added in the same file (but not visible here).

2020-12-03 22:41 UTC, amitc-jahia commented
Requested Changes have been made. Please Review.

2020-12-04 15:02 UTC, laurentfufu requested changes
- with this pattern, resulting stanza will not have the same order as https://github.com/Jahia/paas_jelastic_dx_universal/pull/150/files which should potentially be a problem for future sed update if the haproxy nodes haven't been redeployed since

- still not sure about the backup file benefit because it spoil (in a way) the haproxy's conf folder, maybe keeping it in the root home user with the update version in the suffix in addition to the .bkp one, but basically  IMO, we don't want to rollback the added line so we don't need this backup file

2020-12-04 20:50 UTC, amitc-jahia commented
Following changes have been made. Please review.

- The pattern has been changed to maintain the same order as https://github.com/Jahia/paas_jelastic_dx_universal/pull/150/files and also keeping in mind with the customer `REWRITES`.

- Based on the suggestion of not rolling back to this backup file, the backup file has been removed.

2020-12-08 09:32 UTC, laurentfufu approved these changes

2020-12-08 14:53 UTC, laurentfufu approved these changes

2020-12-08 14:53 UTC, merged