PAAS-1292: generate vault credentials for 3.2.0 update script
Jahia/cloud-scripts pull request #71
Opened 2020-12-09 11:00 UTC by Ronan-Gorain

JIRA issue: https://jira.jahia.org/browse/PAAS-1292

Short description:

2020-12-09 15:06 UTC, laurentfufu submitted a review, later dismissed

2020-12-18 21:11 UTC, adoux requested changes

2020-12-18 21:11 UTC, adoux commented on jahia-cloud-env-update/update-to-3.2.0/update.yml
> +        type: success
we really want to return a success type message?

2020-12-18 21:11 UTC, adoux commented on jahia-cloud-env-update/update-to-3.2.0/update.yml
> +    - log: Store vault creds in en vars
typo :grimacing:

2020-12-21 08:21 UTC, Ronan-Gorain commented on jahia-cloud-env-update/update-to-3.2.0/update.yml
> +        SHORTDOMAIN="paas_${env.shortdomain}"
It seems my rebase was not really successful :)

2020-12-21 08:22 UTC, Ronan-Gorain commented on jahia-cloud-env-update/update-to-3.2.0/update.yml
> +        type: success
it's the way it works

2020-12-21 08:22 UTC, Ronan-Gorain commented on jahia-cloud-env-update/update-to-3.2.0/update.yml
> +    - log: Store vault creds in en vars
fixed

2020-12-21 14:16 UTC, adoux approved these changes

2020-12-21 14:16 UTC, merged