PAAS-1309 force updating datadog agents on ES nodes
Jahia/cloud-scripts pull request #74
Opened 2020-12-14 09:40 UTC by laurentfufu

JIRA issue: https://jira.jahia.org/browse/COPS-1309

Short description:

2020-12-14 09:56 UTC, kevinvandel requested changes

2020-12-14 09:56 UTC, kevinvandel commented on jahia-cloud-env-update/update-to-3.2.0/update.yml
> +      - setupDatadogAgentEs: es   # PAAS-1309
This will not be included in the next release (v3.2.0).
This should either be moved to a "3.3.0" update package, or we wait tomorrow's discussion about release process to decide if we move that to the paas_jelsatic_unomi repository

2020-12-14 09:57 UTC, Ronan-Gorain approved these changes

2020-12-16 12:42 UTC, kevinvandel commented on jahia-cloud-env-update/update-to-3.2.0/update.yml
> +      - setupDatadogAgentEs: es   # PAAS-1309
I created an empty package on paas_jelsatic_unomi repository, @laurentfufu could you please move this action there ?

2020-12-16 12:42 UTC, closed without merging