COPS-253 add moving one node to another HN
Jahia/cloud-scripts pull request #88
Opened 2021-01-25 11:50 UTC by laurentfufu

JIRA issue: https://jira.jahia.org/browse/COPS-253

Short description:

2021-01-25 12:44 UTC, kevinvandel requested changes

2021-01-25 12:44 UTC, kevinvandel commented on jahia/mixins-jahia.yml
> +  getJahiaVersion:
Maybe we should agree on a format for the action names, because the first 3 actions of this file follow a different format (underscores, then dashes, then camelCase) :stuck_out_tongue:

2021-01-25 12:44 UTC, kevinvandel commented on utils/move_one_node.yml
> +id: testlfu
bad name and id

2021-01-25 12:44 UTC, kevinvandel commented on utils/move_one_node.yml
> +---
To be consistent with the rest, filename should contain dashes instead of underscores

2021-01-25 16:00 UTC, kevinvandel approved these changes

2021-01-25 16:15 UTC, laurentfufu commented on jahia/mixins-jahia.yml
> +  getJahiaVersion:
all actions names are now snake case formated

2021-01-25 16:15 UTC, laurentfufu commented on utils/move_one_node.yml
> +id: testlfu
fixed

2021-01-25 16:16 UTC, laurentfufu commented on utils/move_one_node.yml
> +---
fixed

2021-01-26 08:20 UTC, Ronan-Gorain commented on utils/stop-start-env.yml
> +  envsArray = jelastic.environment.control.getenvs("appstore", session)["infos"]
Is there a particuliar reason you didn't used the envlist setting ?
https://docs.cloudscripting.com/creating-manifest/visual-settings/#envlist

2021-01-26 09:03 UTC, laurentfufu commented on utils/stop-start-env.yml
> +  envsArray = jelastic.environment.control.getenvs("appstore", session)["infos"]
because none running env are still grayed out in the list like they can't be selected (but yes they can be selected).
that's bothered me :trollface:

2021-01-26 09:19 UTC, Ronan-Gorain commented on utils/stop-start-env.yml
> +  envsArray = jelastic.environment.control.getenvs("appstore", session)["infos"]
ok ^^

2021-01-26 09:19 UTC, merged